import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b">
          <nav className="mx-auto flex max-w-5xl items-center justify-between p-4">
            <a href="/" className="font-bold text-lg">Khalid Tahir</a>
            <div className="flex gap-5 text-sm">
              <a href="/projects" className="hover:underline">Projects</a>
              <a href="/school" className="hover:underline">School</a>
              <a href="/experience" className="hover:underline">Experience</a>
              <a href="/about" className="hover:underline">About</a>
              <a href="/resume" className="hover:underline">Resume</a>
              <a href="/contact" className="hover:underline">Contact</a>
            </div>
          </nav>
        </header>
        <main className="mx-auto max-w-5xl p-4">{children}</main>
      </body>
    </html>
  )
}

